image_name         := baidunetdisk
version            := 4.17.7
target_src         :=
target_name        := ./distdir/baidunetdisk_$(version)_amd64.deb
target_bin         := /opt/baidunetdisk/baidunetdisk
required_packages  :=


include ../common/common.mk
