FROM debian-base:latest

ARG PKG="fcitx5 fcitx5-rime fcitx5-chinese-addons librime-plugin-lua fcitx5-frontend-gtk3 fcitx5-frontend-gtk4 fcitx5-frontend-qt5 fcitx5-frontend-qt6 fcitx5-config-qt"

USER root
WORKDIR /root

RUN apt install -y ${PKG} && apt clean

USER debian
WORKDIR /home/debian

CMD [ "fcitx5" ]
