FROM debian-base:trixie

ARG PACKAGES

USER root
WORKDIR /root

RUN apt update                  && \
	apt install -y ${PACKAGES}  && \
	apt clean

USER debian
WORKDIR /home/debian

CMD [ "/bin/bash" ]
