image_name         := inkscape
version            := 1.4-6
target_src         := 
target_name        := 
target_bin         := /usr/bin/inkscape
required_packages  := inkscape


include ../common/common.mk
