image_name         := vscode
version            := 1.111.0-1772846623
target_src         :=
target_name        := ./distdir/code_$(version)_amd64.deb
target_bin         := /usr/bin/start.sh
required_packages  :=


include ../common/common.mk
