#!/bin/bash




trap main EXIT


PN=drawio
ARG=($@)

function main {
    case "${ARG[0]}" in
        "install")
            if [[ -n "${ARG[1]}" ]]; then
                PN=${ARG[1]}
                init
                read_package_sh
                setup_use
                fetch_package
                create_dockerfile
                docker_build
            else
                echo "请指定包名"
                exit 1
            fi
            ;;
        "run")
            if [[ -n "${ARG[1]}" ]]; then
                PN=${ARG[1]}
                init
                read_package_sh
                setup_use
                docker_run
            else
                echo "请指定包名"
                exit 1
            fi
            ;;
        "")
            echo "请使用命令：install，run"
            ;;
        *)
            echo "不支持的命令"
            ;;
    esac
}




function init {
    func_title

    IMG=debian:trixie
    CUSER=$USER
    CUID=$UID
    CPKG_REPO_PATH=${HOME}/Desktop/repo
    CPKG_HOME_PATH=${HOME}/Desktop/container

    if [[ ! -e "$CPKG_HOME_PATH" ]]; then
        mkdir -p $CPKG_HOME_PATH
        echo "创建目录：$CPKG_HOME_PATH"
    fi
    if [[ ! -e "$CPKG_REPO_PATH" ]]; then
        mkdir -p $CPKG_REPO_PATH
        echo "创建目录：$CPKG_REPO_PATH"
    fi
}




function read_package_sh {
    func_title
    if [[ ! -e ${CPKG_REPO_PATH}/$PN ]]; then
        echo "找不到软件包：${PN@Q}"
        exit 1
    fi
    SH=$(dir -1 ${CPKG_REPO_PATH}/$PN/*.sh | sort -V | tail -n1)


    PF=$(basename ${SH%.*})
    PV=${PF##*-}
    FS=${CPKG_REPO_PATH}/${PN}/files
    PH=${CPKG_HOME_PATH}/${PN}

    source ${SH}

    echo "SH  = $SH"
    echo "PN  = $PN"
    echo "PV  = $PV"
    echo "PF  = $PF"
    echo "FS  = ${CPKG_REPO_PATH}/${PN}/files"
    echo "PH  = $PH"
    echo "USE = $USE"
    echo "DEP = $DEP"
    echo "SRC = ${SRC}"

    echo ""
}



function fetch_package {
    func_title
    if [[ ! -n "${SRC}" ]]; then
        echo -e "SRC 未设置，跳过 ... \n"
        return
    fi
    if [[ ! -e ${FS} ]]; then
        mkdir -p ${FS}
    fi
    LINK=("${SRC}")
    for i in "${!LINK[@]}"; do
        if [[ "${LINK[$i]##*.}" =~ "deb" ]]; then
            PKG+=("./${LINK[$i]##*/}")
        fi
        echo "LINK[$i] = ${LINK[$i]}"
    done
    for i in "${!PKG[@]}"; do
        echo "PKG[$i]  = ${PKG[$i]}"
    done
    for i in "${!LINK[@]}"; do
        if [[ ! -e "${FS}/${LINK[$i]##*/}" ]]; then
            echo "获取 ${LINK[$i]} -> ${LINK[$i]##*/}"
        else
            echo "已存在 ${LINK[$i]##*/}，跳过 ..."
        fi
    done
    echo ""
}

function create_dockerfile {
    func_title
    echo "创建 ${FS}/dockerfile"
    cat << EOF > ${FS}/dockerfile
FROM ${IMG}

ARG BUILD_DEP=${DEP}
ARG BUILD_PKG=$(echo ${PKG[@]})
ARG http_proxy=${http_proxy}
ARG https_proxy=${https_proxy}

USER root
WORKDIR /root

RUN --mount=type=bind,source=${FS},target=/root/files \
cd /root/files && \
source build_*.sh && \
build_prepare && \
build_depend && \
build_package && \
build_config && \
build_finish

USER ${CUSER}
WORKDIR /home/${CUSER}

CMD [ "/bin/bash" ]
EOF
    echo -e "\e[30m$(cat ${FS}/dockerfile)\e[0m\n"
}

function build_prepare {
    :
}

function build_depend {
    if [[ -n "${BUILD_DEP}" ]]; then
        apt install -y ${BUILD_DEP}
    fi
}

function build_package {
    if [[ -n "${BUILD_PKG}" ]]; then
        apt install -y ${BUILD_PKG}
    fi
}

function build_config {
    :
}

function build_finish {
    apt clean
}


function docker_build {
    func_title
    local build="build_prepare build_depend build_package build_config build_finish"
    for func in ${build}; do
        declare -f ${func} > ${FS}/${func}.sh
        echo "创建 ${FS}/${func}.sh"
        echo -e "\e[30m$(cat ${FS}/${func}.sh)\e[0m"
    done
    echo "构建 docker build --network host -t ${PN}:${PV} ${FS}"
    # docker build --network host -t ${PN}:${PV} ${FS}
    echo ""
}


function setup_use {
    func_title
    if [[ ! -n "${USE}" ]]; then
        echo -e "USE 未设置，跳过 ... \n"
        return
    fi
    for use in ${USE}; do
        case "$use" in
        "wayland")
            RUN_OPTIONS+=("-e WAYLAND_DISPLAY=$WAYLAND_DISPLAY")
            ;;
        "dri")
            RUN_OPTIONS+=("--device /dev/dri")
            ;;
        "dbus")
            RUN_OPTIONS+=("-e DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS -e XDG_RUNTIME_DIR=/run/user/${CUID} -v /run/user/${UID}:/run/user/${CUID} -v /run/dbus/system_bus_socket:/run/dbus/system_bus_socket")
            ;;
        "x11")
            RUN_OPTIONS+=("-e DISPLAY=:0 -e GTK_IM_MODULE=fcitx -e QT_IM_MODULE=fcitx -e XMODIFIERS=@im=fcitx -e GLFW_IM_MODULE=ibus")
            DEP+=" fcitx5-frontend-gtk2 fcitx5-frontend-gtk3 fcitx5-frontend-gtk4 fcitx5-frontend-qt5 fcitx5-frontend-qt6"
            ;;
        "net-host")
            RUN_OPTIONS+=("--network host")
            ;;
        "privileged")
            RUN_OPTIONS+=("--privileged")
            ;;
        "map-tmp")
            RUN_OPTIONS+=("-v /tmp:/tmp")
            ;;
        "map-home")
            RUN_OPTIONS+=("-v ${PH}:/home/${CUSER}")
            if [[ ! -e ${PH} ]]; then mkdir -p ${PH}; fi
            ;;
        "map-fonts")
            RUN_OPTIONS+=("-v ${HOME}/.fonts:/home/${CUSER}/.fonts:ro")
            ;;
        --*)
            RUN_OPTIONS+=("$use")
            ;;
        --*=*)
            RUN_OPTIONS+=("$use")
            ;;
        *=*)
            RUN_OPTIONS+=("--$use")
            ;;
        *)
            echo "未识别：$use"
            exit 1
            ;;
        esac
        printf "%-15s: %s\n" $use "${RUN_OPTIONS[-1]}"
    done
    echo ""
}



function docker_run {
    func_title
    echo "docker run -it --name ${PN} ${RUN_OPTIONS[@]} ${PN}:${PV}"
}






function func_title {
    echo -e "\e[35;1m[ ${FUNCNAME[1]} ]\e[0m"
}

function clog {
    local RESET="\e[0m"
    local RED="\e[31m"
    local GREEN="\e[32m"
    local YELLOW="\e[33m"
    local BLUE="\e[34m"
    local MAGENTA="\e[35m"
    local CYAN="\e[36m"
    local WHITE="\e[37m"
    if $DEBUG; then
        echo -e "${YELLOW}$1${RESET}"
    fi
}
