FROM debian-base:latest

ARG PKG="libappindicator3-1"

USER root
WORKDIR /root

RUN --mount=type=bind,source=./distdir,target=/root/distdir \
    apt install -y /root/distdir/*.deb \
    && apt install -y ${PKG} \
    && apt clean

USER debian
WORKDIR /home/debian

CMD [ "clash-verge" ]
