image_name         := clash
version            := 2.4.4
target_src         := https://github.com/clash-verge-rev/clash-verge-rev/releases/download/v$(version)/Clash.Verge_$(version)_amd64.deb
target_name        := ./distdir/clash-verge_$(version)_amd64.deb
target_bin         := /usr/bin/clash-verge
required_packages  := libappindicator3-1


include ../common/common.mk
