image_name         := amberol
version            := 2025.1-3
target_src         := 
target_name        := 
target_bin         := /usr/bin/amberol
required_packages  := amberol


run_args += -v $$HOME/Music:$(container_home)/Music:ro


include ../common/common.mk
