image_name         := hmcl
version            := 3.8.2
target_src         := https://github.com/HMCL-dev/HMCL/releases/download/v$(version)/HMCL-$(version).sh
target_name        := ./distdir/HMCL-$(version).sh
target_bin         := /home/debian/HMCL-$(version).sh
required_packages  := openjdk-21-jre


include ../common/common.mk
