image_name         := xunlei
version            := 1.0.0.1
target_src         :=
target_name        := ./distdir/com.xunlei.download_$(version)_amd64.deb
target_bin         := /usr/bin/start.sh
required_packages  := libxss1 libnss3 libdbus-glib-1-2


include ../common/common.mk
