FROM debian-base:latest

USER root
WORKDIR /root

RUN --mount=type=bind,source=./distdir,target=/root/distdir \
    apt install -y /root/distdir/*.deb \
    && apt clean

USER debian
WORKDIR /home/debian

CMD [ "drawio", "--enable-features=UseOzonePlatform", "--ozone-platform=wayland", "--disable-features=WaylandWpColorManagerV1", "--force-color-profile=srgb" ]
