image_name         := drawio
version            := 29.0.3
target_src         := https://github.com/jgraph/drawio-desktop/releases/download/v$(version)/drawio-amd64-$(version).deb
target_name        := ./distdir/drawio-amd64-$(version).deb
target_bin         := /usr/bin/start.sh
required_packages  := 


include ../common/common.mk
