image_name         := lx-music
version            := 2.12.0
target_src         := https://github.com/lyswhut/lx-music-desktop/releases/download/v$(version)/lx-music-desktop_$(version)_amd64.deb
target_name        := ./distdir/lx-music-desktop_$(version)_amd64.deb
target_bin         := /usr/bin/lx-music-desktop
required_packages  := 


include ../common/common.mk
