image_name         := wandacloud
version            := 2.0.9
target_src         :=
target_name        := ./distdir/$(version)-linux-amd64.deb
target_bin         :=  /usr/bin/wandacloud
required_packages  :=


include ../common/common.mk
