image_name         := google-chrome
version            := 143.0.7499.109
target_src         := https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_$(version)-1_amd64.deb
target_name        := ./distdir/google-chrome-stable_$(version)-1_amd64.deb
target_bin         := /usr/bin/start.sh
required_packages  :=


include ../common/common.mk
