FROM debian-base:trixie

USER root
WORKDIR /root

RUN apt update                             && \
	apt install -y curl ca-certificates    && \
	curl -s https://repo.waydro.id | bash  && \
	apt install -y waydroid                && \
	apt clean

USER debian
WORKDIR /home/debian

CMD [ "/bin/bash" ]
