image_name         := rhythmbox
version            := 3.4.8-1
target_src         := 
target_name        := 
target_bin         := /usr/bin/rhythmbox
required_packages  := rhythmbox


run_args += -v $$HOME/Music:$(container_home)/Music:rw


include ../common/common.mk
