image_name         := uxplay
version            := 1.71.1-1
target_src         :=
target_name        :=
target_bin         := /usr/bin/start.sh
required_packages  := uxplay gstreamer1.0-plugins-good gstreamer1.0-plugins-bad

# 将 ./files/avahi-dbus.conf 文件复制到系统的 /etc/dbus-1/system.d 目录下

include ../common/common.mk
